In [2]:
import pandas as pd

dataset = pd.read_csv("C:/dataset/2013_pakistan_eq_metadata.csv", header=0)

In [3]:
dataset

,TweetID,CreationTime,Followed,Followers,Geotagged,Label,TotalTweets,TwitterAge,Username,Verified,nHashtags,nMentions,nURLs,DeltaSeconds
0,382813388503412736,Wed Sep 25 10:26:38 +0000 2013,525,500,True,other_useful_information,4074,2013,Waqas Younas,False,3,2,0,0
1,382813391435206659,Wed Sep 25 10:26:39 +0000 2013,499,2537,True,not_related_or_irrelevant,18843,3051,Vajeesh Partab,False,2,2,0,1
2,382813401845485568,Wed Sep 25 10:26:41 +0000 2013,236,220,True,not_related_or_irrelevant,20800,1990,LISA EDENS,False,2,1,1,3
3,382813437513834497,Wed Sep 25 10:26:50 +0000 2013,4197,7605,False,donation_needs_or_offers_or_volunteering_services,180885,2184,"Hayat Alvi, PhD",False,2,3,1,12
4,382813444011204608,Wed Sep 25 10:26:52 +0000 2013,273,116,False,other_useful_information,6623,2512,Faisal Mustafa,False,1,1,1,14
5,382813445495586816,Wed Sep 25 10:26:52 +0000 2013,332,519,True,other_useful_information,20848,1803,Darwesh,False,2,1,0,14
6,382813466014121984,Wed Sep 25 10:26:57 +0000 2013,395,12480,True,not_related_or_irrelevant,25042,2697,Nafees Takar,False,2,2,0,19
7,382813467528282112,Wed Sep 25 10:26:57 +0000 2013,2105,1032,True,injured_or_dead_people,6637,3307,Virginia McMillan,False,2,1,1,19
8,382813501489946624,Wed Sep 25 10:27:05 +0000 2013,154,62,False,injured_or_dead_people,1427,1743,fouzia iftikhar,False,3,1,0,27
9,382813514881982464,Wed Sep 25 10:27:08 +0000 2013,44,1910,False,not_related_or_irrelevant,36948,1715,maria khan,False,2,0,1,30
10,382813518602313729,Wed Sep 25 10:27:09 +0000 2013,857,12254,True,donation_needs_or_offers_or_volunteering_services,58493,2968,Die-Hard Pakistani,False,3,1,0,31
11,382813530396700672,Wed Sep 25 10:27:12 +0000 2013,1389,1743,True,other_useful_information,13093,3625,Joel Bassuk,False,1,2,0,34
12,382813532305096705,Wed Sep 25 10:27:13 +0000 2013,363,21065,False,other_useful_information,26461,3011,farah lodhi khan,False,1,1,0,35
13,382813540366954497,Wed Sep 25 10:27:15 +0000 2013,10,20,False,other_useful_information,35617,2223,Shakemaps M1 - M2,False,1,0,1,37
14,382813540413095936,Wed Sep 25 10:27:15 +0000 2013,10,20,False,injured_or_dead_people,35617,2223,Shakemaps M1 - M2,False,1,0,1,37
15,382813561875361792,Wed Sep 25 10:27:20 +0000 2013,4546,1159,True,missing_trapped_or_found_people,21057,3118,John B. A. Kawecki,False,1,2,0,42
16,382813587410259968,Wed Sep 25 10:27:26 +0000 2013,985,28773,False,injured_or_dead_people,303294,2968,.,False,1,1,0,48
17,382813601024995328,Wed Sep 25 10:27:29 +0000 2013,788,5386,True,donation_needs_or_offers_or_volunteering_services,21074,2957,Furqan T. Siddiqui,False,4,1,0,51
18,382813620356534272,Wed Sep 25 10:27:34 +0000 2013,985,28773,False,donation_needs_or_offers_or_volunteering_services,303294,2968,.,False,3,2,0,56
19,382813652752928768,Wed Sep 25 10:27:41 +0000 2013,371,418,False,injured_or_dead_people,57535,3247,grs,False,2,1,0,63
20,382813700375474176,Wed Sep 25 10:27:53 +0000 2013,681,738,True,other_useful_information,12394,3027,Adnan Kazmy,False,1,0,0,75
21,382813702132867072,Wed Sep 25 10:27:53 +0000 2013,2170,1443,True,other_useful_information,97571,3002,Mr. A Kundi,False,3,2,1,75
22,382813719941484544,Wed Sep 25 10:27:57 +0000 2013,143,56,False,caution_and_advice,5522,2408,MS,False,2,1,0,79
23,382813733623300096,Wed Sep 25 10:28:01 +0000 2013,1242,428,True,other_useful_information,10159,3189,Homosapien,False,1,0,1,83
24,382813761330888704,Wed Sep 25 10:28:07 +0000 2013,813,656,True,other_useful_information,2918,1784,Yasir Hussain,False,3,0,1,89
25,382813788832940033,Wed Sep 25 10:28:14 +0000 2013,1947,5370,True,injured_or_dead_people,37488,3156,New Zealand Doctor,False,2,1,1,96
26,382813812040409089,Wed Sep 25 10:28:19 +0000 2013,63,198,True,other_useful_information,6116,3361,Tamoor Zafar,False,4,0,1,101
27,382813829719019521,Wed Sep 25 10:28:24 +0000 2013,236,4042,True,caution_and_advice,21591,2734,S M Tabish Tariq,False,1,0,1,106
28,382813848006180864,Wed Sep 25 10:28:28 +0000 2013,242,148,False,other_useful_information,5092,3229,Feel Good Inc,False,1,1,0,110
29,382813873679896576,Wed Sep 25 10:28:34 +0000 2013,230,522,True,infrastructure_and_utilities_damage,4275,1751,Bahawal Tariq,False,2,0,0,116
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1530,382837439435669504,Wed Sep 25 12:02:12 +0000 2013,186,46093211,False,other_useful_information,2687,3246,Bill Gates,True,2,0,1,2494
1531,382837443826679808,Wed Sep 25 12:02:14 +0000 2013,286,213,False,injured_or_dead_people,1936,1717,Menahil Ali,False,1,0,0,2496
1532,382837450076217344,Wed Sep 25 12:02:15 +0000 2013,442,9241,True,injured_or_dead_people,34409,2748,Veengas,True,2,1,0,2497
1533,382837466874785792,Wed Sep 25 12:02:19 +0000 2013,921,7091,False,other_useful_information,16783,2984,Amaan Tareen (AT),False,3,1,0,2501
1534,382837479147335681,Wed Sep 25 12:02:22 +0000 2013,274,1200,True,other_useful_information,6917,1706,Shahzad Ahmad,False,2,2,0,2504
1535,382837486143041536,Wed Sep 25 12:02:24 +0000 2013,594,2959,False,donation_needs_or_offers_or_volunteering_services,23425,2393,Zeeshan,False,4,1,0,2506
1536,382837489897316352,Wed Sep 25 12:02:25 +0000 2013,282,20509,True,other_useful_information,38548,3149,Habibies,False,3,0,1,2507
1537,382837500374294528,Wed Sep 25 12:02:27 +0000 2013,2700,1103,True,other_useful_information,28562,3793,Imran,False,2,1,1,2509
1538,382837518955065344,Wed Sep 25 12:02:31 +0000 2013,109,172,False,other_useful_information,4206,1694,hifsa PAT,False,2,1,0,2513
1539,382837519861051392,Wed Sep 25 12:02:32 +0000 2013,110,152,False,donation_needs_or_offers_or_volunteering_services,4159,1694,sadia malik,False,2,1,0,2514
1540,382837523417821185,Wed Sep 25 12:02:33 +0000 2013,1186,3189,False,donation_needs_or_offers_or_volunteering_services,49596,2217,Tiocfaidh Ár Lá,False,3,0,1,2515
1541,382837533391851520,Wed Sep 25 12:02:35 +0000 2013,109,62,False,injured_or_dead_people,4222,1693,samia khan,False,2,1,0,2517
1542,382837568527560704,Wed Sep 25 12:02:43 +0000 2013,94,153,False,not_related_or_irrelevant,840,2566,irfan aziz,False,0,1,0,2525
1543,382837583362809856,Wed Sep 25 12:02:47 +0000 2013,2,1447,True,donation_needs_or_offers_or_volunteering_services,66184,2651,Scene On Hai,False,3,0,1,2529
1544,382837605697474560,Wed Sep 25 12:02:52 +0000 2013,108,14,False,other_useful_information,34,1708,yann maurel junior,False,2,1,1,2534
1545,382837614610358272,Wed Sep 25 12:02:54 +0000 2013,17,422864,False,other_useful_information,212286,1901,Capital TV,False,4,1,0,2536
1546,382837614836858880,Wed Sep 25 12:02:54 +0000 2013,848,859,False,other_useful_information,10702,1919,chinmay das gupta,False,2,1,1,2536
1547,382837626702938112,Wed Sep 25 12:02:57 +0000 2013,1226,1182,False,other_useful_information,25300,2887,rogue naughty,False,2,1,1,2539
1548,382837627281354754,Wed Sep 25 12:02:57 +0000 2013,1762,3758,True,other_useful_information,30586,3381,Ann Tremain Smith ⚜️,False,3,0,0,2539
1549,382814190421168128,Wed Sep 25 10:29:49 +0000 2013,3332,17535,False,injured_or_dead_people,232742,2562,HH,False,2,1,0,191
1550,382830219968909312,Wed Sep 25 11:33:31 +0000 2013,5418,16897,False,donation_needs_or_offers_or_volunteering_services,307660,2651,#New World Order,False,5,0,1,773
1551,382833545179574272,Wed Sep 25 11:46:44 +0000 2013,423,1093,False,other_useful_information,13226,2293,#saveBSOazadLeader,False,3,0,0,1566
1552,382830434167439360,Wed Sep 25 11:34:22 +0000 2013,161,2211,True,donation_needs_or_offers_or_volunteering_services,2204,2852,Pak Fights Polio,False,1,1,1,824
1553,382818863072960512,Wed Sep 25 10:48:24 +0000 2013,605,108032,True,sympathy_and_emotional_support,17092,2905,Sawera Pasha,False,2,0,1,1306
1554,382837135822577664,Wed Sep 25 12:01:00 +0000 2013,453,10630,False,not_related_or_irrelevant,92445,3089,Anas Mallick,False,2,1,0,2422
1555,382836020552929280,Wed Sep 25 11:56:34 +0000 2013,538,4816,False,other_useful_information,6719,1933,TTPTI,False,5,0,0,2156
1556,382830606402351105,Wed Sep 25 11:35:03 +0000 2013,75,494488,False,other_useful_information,112168,3552,Reuters India,True,1,0,0,865
1557,382817567519154176,Wed Sep 25 10:43:15 +0000 2013,0,102207,True,not_related_or_irrelevant,154865,2282,JAAG TV,True,2,0,1,997
1558,382827962930069504,Wed Sep 25 11:24:33 +0000 2013,553,284,False,injured_or_dead_people,66874,2202,AlHamd MarriageBurea,False,10,0,1,3475
1559,382827662109986816,Wed Sep 25 11:23:21 +0000 2013,442,9241,True,donation_needs_or_offers_or_volunteering_services,34409,2748,Veengas,True,7,0,0,3403